version: '3.0'

services:
  # Elasticsearch batcher container
  batcher:
    restart: always
    build:
      context: ./
    command: elasticsearch-batcher
    ports:
      - 8889:8889
    depends_on:
      - elasticsearch
  # elasticsearch instance for testing batcher
  elasticsearch:
    restart: always
    image: elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  # kibana so we can view elasticsearch better
  kibana:
    restart: always
    image: kibana:7.6.1
    ports:
      - 5601:5601
