version: '3.0'

services:
  # Elasticsearch batcher
  batcher:
    restart: always
    build:
      context: ./
    environment:
      - ESB_ES_HOST=http://elasticsearch:9200
      - ESB_FLUSH_INTERVAL_SECONDS=10
    ports:
      - 8889:8889
    depends_on:
      - elasticsearch
  # elasticsearch instance to test batcher service
  elasticsearch:
    restart: always
    image: elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  # kibana to visualize data inside elasticsearch
  kibana:
    restart: always
    image: kibana:7.6.1
    ports:
      - 5601:5601
